[default]
listen_addr = ":8081"
graceful_timeout = 300

[ipinfo]
url = "http://cn.ip.cn/?ip=%s"
regex = '来自：(\S+) (\S+)'
cache_ttl = 86400
ratelimit = 1000

[bid]
aerospike_host = '127.0.0.1'
aerospike_port = 3000
